### ISSUE TITLE
🏆 Awesome and epic initiative from Fernando Correia

### ISSUE THREAD

**Issue by FernandoMCCorreia** [ps-developers-sandbox/NOSGitHubFundamentals#27]
We need to validate first if this is a bug or a feature🤔
Maybe we need to discuss this first.

**Comment by FernandoMCCorreia** [comment]
- [ ] 🎸 A feature from FernandoMCCorreia that rocks
- [ ] ⚡ Another epic feature from FernandoMCCorreia
- [ ] 🔥 Hot feature from FernandoMCCorreia

**Comment by wulfland** [comment]
Comment

- [ ] task 2
- [ ] task 3
